language: python
python:
  - "3.6"

install:
  - pip install -r ./server/requirements.txt

jobs:
  include:
    - stage: "Unit Tests"

      name : "Back end"
      script: python -m unittest discover -s server -p "*_test.py" -v
